- name: Deploy EC2 instances in AWS
  hosts: localhost
  gather_facts: no
  environment:
    AWS_REGION: ap-southeast-4
  vars:
    num_instances: 1
    base_name: sample_ec2_ansible
  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ base_name }}"  # Jinja templating syntax
        description: "{{ base_name }} SSH"
        rules:
          - proto: tcp
            ports: [22]
            cidr_ip: 0.0.0.0/0
      register: aws_security_group

    - name: 'Get all Amazon Linux AMIs'
      amazon.aws.ec2_ami_info:
        owners: amazon
        filters:
          name: al2023-ami-2023.*-x86_64
      register: amazon_linux_amis

    - name: Create EC2 instances with Amazon Linux
      loop: "{{ range(num_instances | int) | list }}"
      amazon.aws.ec2_instance:
        name: "{{ '%s_%d' | format(base_name, item) }}"
        key_name: mykey
        instance_type: t3.micro
        security_group: "{{ aws_security_group.group_id }}"
        image_id: "{{ amazon_linux_amis.images[-1].image_id }}"
        tags:
          Ansible: "{{ base_name }}"