name: Infrastructure Tests

on: push

jobs:
  opentofu_test:
    name: "Run OpenTofu Tests"
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # For Github Actions to work with AWS, it needs to write to be able to issue an OIDC token.
      contents: read  # By default the Github Action can read but not write your repo.
    steps:
    - uses: actions/checkout@v2

    - uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lambda-sample-tests"
        role-session-name: tests-${{ github.run_number }}-${{ github.actor }}
        aws-region: ap-southeast-2

    - uses: opentofu/setup-opentofu@v1

    - name: Tofu Tests
      env:
        TF_VAR_name: lambda-sample-${{ github.run_id }}
      working-directory: ch5/lambda_test
      run: |
        tofu init -backend=false -input=false
        tofu test --verbose
